apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    dev: red
spec:
  containers:
    - image: nginx
      name: my-first-container
      ports:
        - containerPort: 80
#kubectl apply -f pod.yaml
#kubectl run mypod nginx:latest --port=80
#kubectl run mypod nginx:latest ==port=80
#