apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rc
spec:
  replicas: 5
  selector:
    matchLabels:
      app: production
      env: test
  template:
    metadata:
      labels:
        app: production
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80