apiVersion: v1
kind: PersistentVolume
metadata:
  name: safari-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /volumes/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project-tiger
  name: safari-pvc
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: safari
  namespace: project-tiger
  labels:
    app: nginx
spec:

  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
        - name: task-pv-storage
          persistentVolumeClaim:
            claimName: safari-pvc
      containers:
      - name: nginx
        image: httpd:2.4.41-alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/tmp/safari-data"
            name: task-pv-storage