#create a new pod with name admin-pod with
#image busybox allow pod able system time
#the container sleep for 3200 secon
#second challange is to check kube config file to answer this you have to check k config view and check urls and name of cluster user

apiVersion: v1
kind: Pod
metadata:
  name: admin-pod
spec:
  containers:
    - name: admin-container
      image: busybox
      command: ['sh', '-c', 'sleep 3600']
      securityContext:
        capabilities:
          add: ["SYS_TIME" ]