apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff
spec:
  selector:
    app: env
  template:
    metadata:
      labels:
        app: env
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-type
                    operator: NotIn
                    values:
                      - extremelyslow
                      -

      containers:
        - image: nginx
          name: fif