apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodename-deploy

spec:
  replicas: 2
  selector:
    matchLabels:
      app: env
  template:
    metadata:
      name: first
      labels:
        app: env
    spec:
      nodeName: gke-cluster-1-default-pool-a26b08f8-1ppg
      containers:
        - name: node-conta
          image: nginx
