apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeselector-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      env: test
  template:
    metadata:
      name: firstpod
      labels:
        env: test
    spec:
      nodeSelector:
        disk: ssd
      containers:
        - image: nginx
          name: firstcont



