apiVersion: apps/v1
kind: Deployment
metadata:
  name: req-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: req-pod
      labels:
        env: dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: disk
                    operator: In
                    values:
                      - ssd
      containers:
        - image: nginx
          name: req-container