apiVersion: v1
kind: PersistentVolume
metadata:
  name: cka-pv
  labels:
    type: local
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: manual
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cka-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Mi
  storageClassName: manual

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cka-deployment
  labels:
    app: nginx
spec:
  strategy:
    type: Recreate
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: mysql
        image: devopstitan/cka-exam:mysql-question-09
        ports:
        - containerPort: 3306
          name: mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cka-secret
                key: password
        volumeMounts:
          - name: mysql-volume
            mountPath: /var/lib/mysql

      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: cka-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: cka-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 3306
