apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  restartPolicy: Never
  containers:
    - name: busybox1
      image: busybox
      command:
        ['sh','-c','while true; do echo sucess > /output/output.txt; sleep 5 done']
      volumeMounts:
        - name: empty
          mountPath: /output
    - image: busybox
      name: busybox2
      command:
        ['sh','-c','while true; do cat /input/output.txt; sleep 5; done']
      volumeMounts:
        - name: empty
          mountPath: /input
  volumes:
    - name: empty
      emptyDir: {}
