apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  nodeName: worker-1
  volumes:
    - name: myvol
      persistentVolumeClaim:
        claimName: my-pvc
  containers:
    - name: first
      image: nginx
      ports:
        - containerPort: 80
          name: hht
      volumeMounts:
        - name: myvol
          mountPath: /usr/share/nginx/html
