apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  containers:
    - name: first
      image: nginx
      volumeMounts:
        - name: useme
          mountPath: /var/lib
    - name: second
      image: busybox
      command: ["/bin/sh"]
      args:
        ["-c", "while true; do sleep 30; done;"]
      volumeMounts:
        - mountPath: /vatl/l
        - name: empty-dir-volume

  volumes:
    - name: useme
    - emptyDir: {}
