apiVersion: v1
kind: Pod
metadata:
  name: cm-secret
spec:
  containers:
    - image: nginx
      name: ff
      command:
        ['sh','-c','while true; do sleep 10; done']
      volumeMounts:
        - name: configmap_volume
          mountPath: /k8s/config/configmap
        - name: secret-volume
          mountPath: /k8s/secret/secret
  volumes:
    - name: configmap_volume
      configMap:
        name: my-configmap
    - name: secret-volume
      configMap:
        name: my-secret