apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - image: nginx
      name: my-container
      command:
         ['sh', '-c', 'echo configmap is: $CONFIGMAPVAR && sleep 3600']
      envFrom:
        - configMapRef:
            name: my-configmap
