apiVersion: v1
kind: Pod
metadata:
  name: tmulti-container-pod
spec:

  restartPolicy: Never

  volumes:
  - name: main-volume
    emptyDir: {}

  containers:

  - name: main
    image: busybox:1.28
    command: [ "/bin/sh" ]
    args: [ "-c", "i=0; while true; do echo “$i: $(date)” >> /var/log/cka-exam.log; i=$((i+1));
 sleep 1; done" ]
    volumeMounts:
    - name: main-volume
      mountPath: /var/log

  - name: sidecar
    image: busybox:1.28
    command: [ "/bin/sh" ]
    args: [ "-c", "tail -n+1 -F /var/log/cka-exam.log" ]
    volumeMounts:
    - name: main-volume
      mountPath: /var/log
