apiVersion: v1
kind: Pod
metadata:
  namespace: cka-ns
  name: cka-pod
spec:
  containers:
    - name: cka-container
      image: nginx
  tolerations:
    - key: node-role.kubernetes.io/control-plane
      effect: NoSchedule
  nodeSelector:
    node-role.kubernetes.io/control-plane: ""
